{% set name = "nanoarrow" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nanoarrow-{{ version }}.tar.gz
  sha256: 5d6b6e5609671c42e9ec85b195664f8bb6d721dd3a3de56fcbd8b9ed62e38af8

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61.0.0
    - cython
    - pip
  run:
    - python

test:
  imports:
    - nanoarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arrow.apache.org/nanoarrow/
  summary: Python bindings to the nanoarrow C library
  dev_url: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paleolimbot
