{% set name = "nanoarrow" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/apache/arrow-nanoarrow/archive/refs/tags/apache-arrow-nanoarrow-{{ version }}.tar.gz
  sha256: ff21a8286bbbb1a9d631de9af2dea07ea4aa8b8c13e22d65793fb455f41c03e5

build:
  number: 1

outputs:
  - name: libnanoarrow
    script: build-lib.sh  # [unix]
    script: build-lib.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libnanoarrow', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
      host:
        - zstd
        - lz4-c
    test:
      commands:
        - test -f $PREFIX/include/nanoarrow/nanoarrow.h  # [unix]
        - if not exist %LIBRARY_INC%\\nanoarrow\\nanoarrow.h exit 1  # [win]

  - name: nanoarrow
    script: build.sh  # [unix]
    script: build.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - meson-python                           # [build_platform != target_platform]
      host:
        - python
        - meson-python
        - python-build
        - cython
        - pip
        - zstd
      run:
        - python
        - zstd
    test:
      imports:
        - nanoarrow
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://arrow.apache.org/nanoarrow/
  summary: Python bindings to the nanoarrow C library
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paleolimbot
