{% set name = "nanoarrow" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nanoarrow-{{ version }}.tar.gz
  sha256: e333e639f02d97c01834c8e3fd25fb945ed53196bdfaeb129dd5a7b9f4233d39

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('c++') }}
    - {{ stdlib("c++") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - python
    - meson-python
    - cython
    - pip
    - zstd
  run:
    - python
    - zstd

test:
  imports:
    - nanoarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://arrow.apache.org/nanoarrow/
  summary: Python bindings to the nanoarrow C library
  dev_url: https://github.com/apache/arrow-nanoarrow
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paleolimbot
